namespace ReaderSDK
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variables.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources that are currently in use.
        /// </summary>
        /// <param name="disposing">True if managed resources should be released; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Code generated by the form designer.

        /// <summary>
        /// The designer supports the required methods - do not modify them.
        /// Use a code editor to modify the content of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.mnuBar = new System.Windows.Forms.MenuStrip();
            this.tsmiConnect = new System.Windows.Forms.ToolStripMenuItem();
            this.tsmiMsg = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.tsmiUserManual = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.tsmiAboutMe = new System.Windows.Forms.ToolStripMenuItem();
            this.statusBar = new System.Windows.Forms.StatusStrip();
            this.tsStatusPortOpen = new System.Windows.Forms.ToolStripStatusLabel();
            this.tsStatusPort = new System.Windows.Forms.ToolStripStatusLabel();
            this.tsStatusBr = new System.Windows.Forms.ToolStripStatusLabel();
            this.tsFWVersion = new System.Windows.Forms.ToolStripStatusLabel();
            this.tsStatusInfo = new System.Windows.Forms.ToolStripStatusLabel();
            this.tmrClock = new System.Windows.Forms.Timer(this.components);
            this.pnlInformation = new System.Windows.Forms.Panel();
            this.statusListView1 = new ADControlsLib.Windows.Forms.StatusListView();
            this.mnuBar.SuspendLayout();
            this.statusBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // mnuBar
            // 
            this.mnuBar.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.mnuBar.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsmiConnect});
            this.mnuBar.Location = new System.Drawing.Point(0, 0);
            this.mnuBar.Name = "mnuBar";
            this.mnuBar.Size = new System.Drawing.Size(960, 28);
            this.mnuBar.TabIndex = 46;
            this.mnuBar.Text = "menuStrip1";
            this.mnuBar.ItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.mnuBar_ItemClicked);
            // 
            // tsmiConnect
            // 
            this.tsmiConnect.Name = "tsmiConnect";
            this.tsmiConnect.Size = new System.Drawing.Size(77, 24);
            this.tsmiConnect.Text = "Connect";
            this.tsmiConnect.Click += new System.EventHandler(this.tsmiConnect_Click);
            // 
            // tsmiMsg
            // 
            this.tsmiMsg.Name = "tsmiMsg";
            this.tsmiMsg.Size = new System.Drawing.Size(200, 22);
            this.tsmiMsg.Text = "Real-time information";
            // 
            // toolStripSeparator3
            // 
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new System.Drawing.Size(197, 6);
            // 
            // tsmiUserManual
            // 
            this.tsmiUserManual.Name = "tsmiUserManual";
            this.tsmiUserManual.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.F1)));
            this.tsmiUserManual.Size = new System.Drawing.Size(200, 22);
            this.tsmiUserManual.Text = "User Manual";
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(197, 6);
            // 
            // tsmiAboutMe
            // 
            this.tsmiAboutMe.Name = "tsmiAboutMe";
            this.tsmiAboutMe.Size = new System.Drawing.Size(200, 22);
            this.tsmiAboutMe.Text = "&About ";
            // 
            // statusBar
            // 
            this.statusBar.AutoSize = false;
            this.statusBar.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.statusBar.GripStyle = System.Windows.Forms.ToolStripGripStyle.Visible;
            this.statusBar.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.statusBar.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.tsStatusPortOpen,
            this.tsStatusPort,
            this.tsStatusBr,
            this.tsFWVersion,
            this.tsStatusInfo});
            this.statusBar.Location = new System.Drawing.Point(0, 676);
            this.statusBar.Name = "statusBar";
            this.statusBar.Size = new System.Drawing.Size(960, 24);
            this.statusBar.SizingGrip = false;
            this.statusBar.TabIndex = 47;
            this.statusBar.Text = "statusStrip1";
            // 
            // tsStatusPortOpen
            // 
            this.tsStatusPortOpen.AutoSize = false;
            this.tsStatusPortOpen.BorderSides = ((System.Windows.Forms.ToolStripStatusLabelBorderSides)((System.Windows.Forms.ToolStripStatusLabelBorderSides.Left | System.Windows.Forms.ToolStripStatusLabelBorderSides.Right)));
            this.tsStatusPortOpen.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tsStatusPortOpen.Name = "tsStatusPortOpen";
            this.tsStatusPortOpen.Size = new System.Drawing.Size(100, 18);
            this.tsStatusPortOpen.Text = "CLOSE   ";
            // 
            // tsStatusPort
            // 
            this.tsStatusPort.AutoSize = false;
            this.tsStatusPort.BorderSides = ((System.Windows.Forms.ToolStripStatusLabelBorderSides)((System.Windows.Forms.ToolStripStatusLabelBorderSides.Left | System.Windows.Forms.ToolStripStatusLabelBorderSides.Right)));
            this.tsStatusPort.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tsStatusPort.Name = "tsStatusPort";
            this.tsStatusPort.Size = new System.Drawing.Size(120, 18);
            this.tsStatusPort.Text = "COM?";
            // 
            // tsStatusBr
            // 
            this.tsStatusBr.AutoSize = false;
            this.tsStatusBr.BorderSides = ((System.Windows.Forms.ToolStripStatusLabelBorderSides)((System.Windows.Forms.ToolStripStatusLabelBorderSides.Left | System.Windows.Forms.ToolStripStatusLabelBorderSides.Right)));
            this.tsStatusBr.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tsStatusBr.Name = "tsStatusBr";
            this.tsStatusBr.Size = new System.Drawing.Size(80, 18);
            this.tsStatusBr.Text = "115200";
            // 
            // tsFWVersion
            // 
            this.tsFWVersion.AutoSize = false;
            this.tsFWVersion.BorderSides = ((System.Windows.Forms.ToolStripStatusLabelBorderSides)((System.Windows.Forms.ToolStripStatusLabelBorderSides.Left | System.Windows.Forms.ToolStripStatusLabelBorderSides.Right)));
            this.tsFWVersion.Name = "tsFWVersion";
            this.tsFWVersion.Size = new System.Drawing.Size(260, 18);
            this.tsFWVersion.Text = "Firmware Version";
            // 
            // tsStatusInfo
            // 
            this.tsStatusInfo.BorderSides = System.Windows.Forms.ToolStripStatusLabelBorderSides.Left;
            this.tsStatusInfo.Name = "tsStatusInfo";
            this.tsStatusInfo.Size = new System.Drawing.Size(385, 18);
            this.tsStatusInfo.Spring = true;
            this.tsStatusInfo.Text = "  Status..";
            this.tsStatusInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tmrClock
            // 
            this.tmrClock.Enabled = true;
            this.tmrClock.Interval = 200;
            this.tmrClock.Tick += new System.EventHandler(this.tmrClock_Tick);
            // 
            // pnlInformation
            // 
            this.pnlInformation.AutoScroll = true;
            this.pnlInformation.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlInformation.Location = new System.Drawing.Point(0, 28);
            this.pnlInformation.Name = "pnlInformation";
            this.pnlInformation.Size = new System.Drawing.Size(960, 518);
            this.pnlInformation.TabIndex = 48;
            // 
            // statusListView1
            // 
            this.statusListView1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.statusListView1.IsShowStatus = true;
            this.statusListView1.Location = new System.Drawing.Point(0, 546);
            this.statusListView1.Name = "statusListView1";
            this.statusListView1.Size = new System.Drawing.Size(960, 130);
            this.statusListView1.TabIndex = 49;
            // 
            // frmMain
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.ClientSize = new System.Drawing.Size(960, 700);
            this.Controls.Add(this.pnlInformation);
            this.Controls.Add(this.statusListView1);
            this.Controls.Add(this.statusBar);
            this.Controls.Add(this.mnuBar);
            this.Font = new System.Drawing.Font("Microsoft YaHei", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MainMenuStrip = this.mnuBar;
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Manager Reader";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmMain_FormClosing);
            this.Load += new System.EventHandler(this.frmMain_Load);
            this.mnuBar.ResumeLayout(false);
            this.mnuBar.PerformLayout();
            this.statusBar.ResumeLayout(false);
            this.statusBar.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip mnuBar;
        private System.Windows.Forms.ToolStripMenuItem tsmiConnect;
        private System.Windows.Forms.ToolStripMenuItem tsmiMsg;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
        private System.Windows.Forms.ToolStripMenuItem tsmiUserManual;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem tsmiAboutMe;
        private System.Windows.Forms.StatusStrip statusBar;
        private System.Windows.Forms.ToolStripStatusLabel tsStatusPortOpen;
        private System.Windows.Forms.ToolStripStatusLabel tsStatusPort;
        private System.Windows.Forms.ToolStripStatusLabel tsStatusBr;
        private System.Windows.Forms.ToolStripStatusLabel tsFWVersion;
        private System.Windows.Forms.ToolStripStatusLabel tsStatusInfo;
        private System.Windows.Forms.Timer tmrClock;
        private System.Windows.Forms.Panel pnlInformation;
        private ADControlsLib.Windows.Forms.StatusListView statusListView1;
    }
}

