namespace ReaderSDK
{
    partial class ucMReadDemo
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by the component designer

        /// <summary>
        /// Method required for designer support - do not modify
        /// Use the code editor to modify the contents of this method.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.btnReadMultiple = new System.Windows.Forms.Button();
            this.btnClearScreen = new System.Windows.Forms.Button();
            this.pnlAction = new System.Windows.Forms.Panel();
            this.btnSingleRead = new System.Windows.Forms.Button();
            this.btnExport = new System.Windows.Forms.Button();
            this.tmrClock = new System.Windows.Forms.Timer(this.components);
            this.ledCurrentAnt = new ADControlsLib.Windows.Forms.LxLedControl();
            this.lblCurrentAnt = new System.Windows.Forms.Label();
            this.nudInventoryInterval = new System.Windows.Forms.NumericUpDown();
            this.nudInventoryCount = new System.Windows.Forms.NumericUpDown();
            this.lblInventoryCount = new System.Windows.Forms.Label();
            this.nudRunTimes = new System.Windows.Forms.NumericUpDown();
            this.lblRunTimes = new System.Windows.Forms.Label();
            this.nudMaxTag = new System.Windows.Forms.NumericUpDown();
            this.ledAllTimes = new ADControlsLib.Windows.Forms.LxLedControl();
            this.lblAllTimes = new System.Windows.Forms.Label();
            this.lblInventoryInterval = new System.Windows.Forms.Label();
            this.lblMaxTag = new System.Windows.Forms.Label();
            this.ledInventoryTimes = new ADControlsLib.Windows.Forms.LxLedControl();
            this.lblInventoryTimes = new System.Windows.Forms.Label();
            this.ledInventoryTags = new ADControlsLib.Windows.Forms.LxLedControl();
            this.lblInventoryTags = new System.Windows.Forms.Label();
            this.ledAllTags = new ADControlsLib.Windows.Forms.LxLedControl();
            this.lblAllTags = new System.Windows.Forms.Label();
            this.pnlMsg = new System.Windows.Forms.Panel();
            this.listViewEPC = new System.Windows.Forms.ListView();
            this.cNumber = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cPC = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cEPC = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cCRC = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cDATA = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cCnt = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cAnt = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.cRssi = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.btnToggleAutoCycle = new System.Windows.Forms.Button();
            this.pnlAction.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ledCurrentAnt)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudInventoryInterval)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudInventoryCount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudRunTimes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxTag)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledAllTimes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledInventoryTimes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledInventoryTags)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledAllTags)).BeginInit();
            this.pnlMsg.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnReadMultiple
            // 
            this.btnReadMultiple.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnReadMultiple.Location = new System.Drawing.Point(3, 3);
            this.btnReadMultiple.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnReadMultiple.Name = "btnReadMultiple";
            this.btnReadMultiple.Size = new System.Drawing.Size(160, 34);
            this.btnReadMultiple.TabIndex = 35;
            this.btnReadMultiple.Text = "  Start Reading Tags";
            this.btnReadMultiple.UseVisualStyleBackColor = true;
            this.btnReadMultiple.Click += new System.EventHandler(this.btnReadMultiple_Click);
            // 
            // btnClearScreen
            // 
            this.btnClearScreen.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnClearScreen.Location = new System.Drawing.Point(163, 3);
            this.btnClearScreen.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnClearScreen.Name = "btnClearScreen";
            this.btnClearScreen.Size = new System.Drawing.Size(160, 34);
            this.btnClearScreen.TabIndex = 35;
            this.btnClearScreen.Text = "Clear Screen";
            this.btnClearScreen.UseVisualStyleBackColor = true;
            this.btnClearScreen.Click += new System.EventHandler(this.btnClearScreen_Click);
            // 
            // pnlAction
            // 
            this.pnlAction.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlAction.Controls.Add(this.btnToggleAutoCycle);
            this.pnlAction.Controls.Add(this.btnSingleRead);
            this.pnlAction.Controls.Add(this.btnExport);
            this.pnlAction.Controls.Add(this.btnClearScreen);
            this.pnlAction.Controls.Add(this.btnReadMultiple);
            this.pnlAction.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlAction.Location = new System.Drawing.Point(0, 638);
            this.pnlAction.Name = "pnlAction";
            this.pnlAction.Padding = new System.Windows.Forms.Padding(3);
            this.pnlAction.Size = new System.Drawing.Size(900, 42);
            this.pnlAction.TabIndex = 72;
            // 
            // btnSingleRead
            // 
            this.btnSingleRead.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnSingleRead.Location = new System.Drawing.Point(483, 3);
            this.btnSingleRead.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.btnSingleRead.Name = "btnSingleRead";
            this.btnSingleRead.Size = new System.Drawing.Size(160, 34);
            this.btnSingleRead.TabIndex = 38;
            this.btnSingleRead.Text = "Single Read";
            this.btnSingleRead.UseVisualStyleBackColor = true;
            this.btnSingleRead.Click += new System.EventHandler(this.btnSingleRead_Click);
            // 
            // btnExport
            // 
            this.btnExport.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnExport.Location = new System.Drawing.Point(323, 3);
            this.btnExport.Margin = new System.Windows.Forms.Padding(3, 5, 3, 5);
            this.btnExport.Name = "btnExport";
            this.btnExport.Size = new System.Drawing.Size(160, 34);
            this.btnExport.TabIndex = 37;
            this.btnExport.TabStop = false;
            this.btnExport.Text = "Export";
            this.btnExport.UseVisualStyleBackColor = true;
            this.btnExport.Click += new System.EventHandler(this.btnExport_Click);
            // 
            // tmrClock
            // 
            this.tmrClock.Enabled = true;
            this.tmrClock.Interval = 10;
            this.tmrClock.Tick += new System.EventHandler(this.tmrClock_Tick);
            // 
            // ledCurrentAnt
            // 
            this.ledCurrentAnt.BackColor = System.Drawing.Color.Transparent;
            this.ledCurrentAnt.BackColor_1 = System.Drawing.Color.Transparent;
            this.ledCurrentAnt.BackColor_2 = System.Drawing.Color.DarkRed;
            this.ledCurrentAnt.BevelRate = 0.1F;
            this.ledCurrentAnt.BorderColor = System.Drawing.Color.Lavender;
            this.ledCurrentAnt.BorderWidth = 3;
            this.ledCurrentAnt.FadedColor = System.Drawing.SystemColors.ControlLight;
            this.ledCurrentAnt.FocusedBorderColor = System.Drawing.Color.LightCoral;
            this.ledCurrentAnt.ForeColor = System.Drawing.Color.Blue;
            this.ledCurrentAnt.HighlightOpaque = ((byte)(20));
            this.ledCurrentAnt.Location = new System.Drawing.Point(320, 3);
            this.ledCurrentAnt.Name = "ledCurrentAnt";
            this.ledCurrentAnt.SegmentIntervalRatio = 50;
            this.ledCurrentAnt.ShowHighlight = true;
            this.ledCurrentAnt.Size = new System.Drawing.Size(128, 24);
            this.ledCurrentAnt.TabIndex = 2300;
            this.ledCurrentAnt.TabStop = false;
            this.ledCurrentAnt.Text = "0";
            this.ledCurrentAnt.TextAlignment = ADControlsLib.Windows.Forms.LxLedControl.Alignment.Right;
            this.ledCurrentAnt.TotalCharCount = 2;
            // 
            // lblCurrentAnt
            // 
            this.lblCurrentAnt.AutoSize = true;
            this.lblCurrentAnt.Location = new System.Drawing.Point(200, 6);
            this.lblCurrentAnt.Name = "lblCurrentAnt";
            this.lblCurrentAnt.Size = new System.Drawing.Size(98, 20);
            this.lblCurrentAnt.TabIndex = 2299;
            this.lblCurrentAnt.Text = "Current Ant:";
            this.lblCurrentAnt.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nudInventoryInterval
            // 
            this.nudInventoryInterval.Location = new System.Drawing.Point(836, 63);
            this.nudInventoryInterval.Maximum = new decimal(new int[] {
            800,
            0,
            0,
            0});
            this.nudInventoryInterval.Name = "nudInventoryInterval";
            this.nudInventoryInterval.Size = new System.Drawing.Size(44, 27);
            this.nudInventoryInterval.TabIndex = 2294;
            this.nudInventoryInterval.Value = new decimal(new int[] {
            50,
            0,
            0,
            0});
            // 
            // nudInventoryCount
            // 
            this.nudInventoryCount.Location = new System.Drawing.Point(620, 93);
            this.nudInventoryCount.Maximum = new decimal(new int[] {
            800,
            0,
            0,
            0});
            this.nudInventoryCount.Name = "nudInventoryCount";
            this.nudInventoryCount.Size = new System.Drawing.Size(48, 27);
            this.nudInventoryCount.TabIndex = 2290;
            // 
            // lblInventoryCount
            // 
            this.lblInventoryCount.AutoSize = true;
            this.lblInventoryCount.Location = new System.Drawing.Point(470, 96);
            this.lblInventoryCount.Name = "lblInventoryCount";
            this.lblInventoryCount.Size = new System.Drawing.Size(188, 20);
            this.lblInventoryCount.TabIndex = 2289;
            this.lblInventoryCount.Text = "Stop for Inventory(num):";
            this.lblInventoryCount.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nudRunTimes
            // 
            this.nudRunTimes.Location = new System.Drawing.Point(620, 63);
            this.nudRunTimes.Maximum = new decimal(new int[] {
            800,
            0,
            0,
            0});
            this.nudRunTimes.Name = "nudRunTimes";
            this.nudRunTimes.Size = new System.Drawing.Size(48, 27);
            this.nudRunTimes.TabIndex = 2288;
            // 
            // lblRunTimes
            // 
            this.lblRunTimes.AutoSize = true;
            this.lblRunTimes.Location = new System.Drawing.Point(470, 66);
            this.lblRunTimes.Name = "lblRunTimes";
            this.lblRunTimes.Size = new System.Drawing.Size(186, 20);
            this.lblRunTimes.TabIndex = 2287;
            this.lblRunTimes.Text = "Stop for Run Times(sec):";
            this.lblRunTimes.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nudMaxTag
            // 
            this.nudMaxTag.Location = new System.Drawing.Point(620, 33);
            this.nudMaxTag.Maximum = new decimal(new int[] {
            800,
            0,
            0,
            0});
            this.nudMaxTag.Name = "nudMaxTag";
            this.nudMaxTag.Size = new System.Drawing.Size(48, 27);
            this.nudMaxTag.TabIndex = 2286;
            this.nudMaxTag.Value = new decimal(new int[] {
            80,
            0,
            0,
            0});
            // 
            // ledAllTimes
            // 
            this.ledAllTimes.BackColor = System.Drawing.Color.Transparent;
            this.ledAllTimes.BackColor_1 = System.Drawing.Color.Transparent;
            this.ledAllTimes.BackColor_2 = System.Drawing.Color.DarkRed;
            this.ledAllTimes.BevelRate = 0.1F;
            this.ledAllTimes.BorderColor = System.Drawing.Color.Lavender;
            this.ledAllTimes.BorderWidth = 3;
            this.ledAllTimes.FadedColor = System.Drawing.SystemColors.ControlLight;
            this.ledAllTimes.FocusedBorderColor = System.Drawing.Color.LightCoral;
            this.ledAllTimes.ForeColor = System.Drawing.Color.Red;
            this.ledAllTimes.HighlightOpaque = ((byte)(20));
            this.ledAllTimes.Location = new System.Drawing.Point(320, 92);
            this.ledAllTimes.Name = "ledAllTimes";
            this.ledAllTimes.SegmentIntervalRatio = 50;
            this.ledAllTimes.ShowHighlight = true;
            this.ledAllTimes.Size = new System.Drawing.Size(128, 24);
            this.ledAllTimes.TabIndex = 2285;
            this.ledAllTimes.TabStop = false;
            this.ledAllTimes.Text = "0";
            this.ledAllTimes.TextAlignment = ADControlsLib.Windows.Forms.LxLedControl.Alignment.Right;
            this.ledAllTimes.TotalCharCount = 10;
            // 
            // lblAllTimes
            // 
            this.lblAllTimes.AutoSize = true;
            this.lblAllTimes.Location = new System.Drawing.Point(200, 96);
            this.lblAllTimes.Name = "lblAllTimes";
            this.lblAllTimes.Size = new System.Drawing.Size(105, 20);
            this.lblAllTimes.TabIndex = 2284;
            this.lblAllTimes.Text = "Run Times(s):";
            this.lblAllTimes.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblInventoryInterval
            // 
            this.lblInventoryInterval.AutoSize = true;
            this.lblInventoryInterval.Location = new System.Drawing.Point(690, 66);
            this.lblInventoryInterval.Name = "lblInventoryInterval";
            this.lblInventoryInterval.Size = new System.Drawing.Size(171, 20);
            this.lblInventoryInterval.TabIndex = 2283;
            this.lblInventoryInterval.Text = "Inventory Interval(ms):";
            this.lblInventoryInterval.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblMaxTag
            // 
            this.lblMaxTag.AutoSize = true;
            this.lblMaxTag.Location = new System.Drawing.Point(470, 36);
            this.lblMaxTag.Name = "lblMaxTag";
            this.lblMaxTag.Size = new System.Drawing.Size(152, 20);
            this.lblMaxTag.TabIndex = 2272;
            this.lblMaxTag.Text = "Stop for Tags(tags):";
            this.lblMaxTag.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // ledInventoryTimes
            // 
            this.ledInventoryTimes.BackColor = System.Drawing.Color.Transparent;
            this.ledInventoryTimes.BackColor_1 = System.Drawing.Color.Transparent;
            this.ledInventoryTimes.BackColor_2 = System.Drawing.Color.DarkRed;
            this.ledInventoryTimes.BevelRate = 0.1F;
            this.ledInventoryTimes.BorderColor = System.Drawing.Color.Lavender;
            this.ledInventoryTimes.BorderWidth = 3;
            this.ledInventoryTimes.FadedColor = System.Drawing.SystemColors.ControlLight;
            this.ledInventoryTimes.FocusedBorderColor = System.Drawing.Color.LightCoral;
            this.ledInventoryTimes.ForeColor = System.Drawing.Color.Green;
            this.ledInventoryTimes.HighlightOpaque = ((byte)(20));
            this.ledInventoryTimes.Location = new System.Drawing.Point(320, 32);
            this.ledInventoryTimes.Name = "ledInventoryTimes";
            this.ledInventoryTimes.SegmentIntervalRatio = 50;
            this.ledInventoryTimes.ShowHighlight = true;
            this.ledInventoryTimes.Size = new System.Drawing.Size(128, 24);
            this.ledInventoryTimes.TabIndex = 2274;
            this.ledInventoryTimes.TabStop = false;
            this.ledInventoryTimes.Text = "0";
            this.ledInventoryTimes.TextAlignment = ADControlsLib.Windows.Forms.LxLedControl.Alignment.Right;
            this.ledInventoryTimes.TotalCharCount = 7;
            // 
            // lblInventoryTimes
            // 
            this.lblInventoryTimes.AutoSize = true;
            this.lblInventoryTimes.Location = new System.Drawing.Point(200, 36);
            this.lblInventoryTimes.Name = "lblInventoryTimes";
            this.lblInventoryTimes.Size = new System.Drawing.Size(146, 20);
            this.lblInventoryTimes.TabIndex = 2270;
            this.lblInventoryTimes.Text = "Inventory Times(s):";
            this.lblInventoryTimes.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // ledInventoryTags
            // 
            this.ledInventoryTags.BackColor = System.Drawing.Color.Transparent;
            this.ledInventoryTags.BackColor_1 = System.Drawing.Color.Transparent;
            this.ledInventoryTags.BackColor_2 = System.Drawing.Color.DarkRed;
            this.ledInventoryTags.BevelRate = 0.1F;
            this.ledInventoryTags.BorderColor = System.Drawing.Color.Lavender;
            this.ledInventoryTags.BorderWidth = 3;
            this.ledInventoryTags.FadedColor = System.Drawing.SystemColors.ControlLight;
            this.ledInventoryTags.FocusedBorderColor = System.Drawing.Color.LightCoral;
            this.ledInventoryTags.ForeColor = System.Drawing.Color.Red;
            this.ledInventoryTags.HighlightOpaque = ((byte)(20));
            this.ledInventoryTags.Location = new System.Drawing.Point(22, 42);
            this.ledInventoryTags.Name = "ledInventoryTags";
            this.ledInventoryTags.SegmentIntervalRatio = 50;
            this.ledInventoryTags.ShowHighlight = true;
            this.ledInventoryTags.Size = new System.Drawing.Size(140, 44);
            this.ledInventoryTags.TabIndex = 2273;
            this.ledInventoryTags.TabStop = false;
            this.ledInventoryTags.Text = "0";
            this.ledInventoryTags.TextAlignment = ADControlsLib.Windows.Forms.LxLedControl.Alignment.Right;
            this.ledInventoryTags.TotalCharCount = 6;
            // 
            // lblInventoryTags
            // 
            this.lblInventoryTags.Location = new System.Drawing.Point(42, 6);
            this.lblInventoryTags.Name = "lblInventoryTags";
            this.lblInventoryTags.Size = new System.Drawing.Size(100, 30);
            this.lblInventoryTags.TabIndex = 79;
            this.lblInventoryTags.Text = "Inventory tags :";
            this.lblInventoryTags.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // ledAllTags
            // 
            this.ledAllTags.BackColor = System.Drawing.Color.Transparent;
            this.ledAllTags.BackColor_1 = System.Drawing.Color.Transparent;
            this.ledAllTags.BackColor_2 = System.Drawing.Color.DarkRed;
            this.ledAllTags.BevelRate = 0.1F;
            this.ledAllTags.BorderColor = System.Drawing.Color.Lavender;
            this.ledAllTags.BorderWidth = 3;
            this.ledAllTags.FadedColor = System.Drawing.SystemColors.ControlLight;
            this.ledAllTags.FocusedBorderColor = System.Drawing.Color.LightCoral;
            this.ledAllTags.ForeColor = System.Drawing.Color.Red;
            this.ledAllTags.HighlightOpaque = ((byte)(20));
            this.ledAllTags.Location = new System.Drawing.Point(320, 62);
            this.ledAllTags.Name = "ledAllTags";
            this.ledAllTags.SegmentIntervalRatio = 50;
            this.ledAllTags.ShowHighlight = true;
            this.ledAllTags.Size = new System.Drawing.Size(128, 24);
            this.ledAllTags.TabIndex = 2281;
            this.ledAllTags.TabStop = false;
            this.ledAllTags.Text = "0";
            this.ledAllTags.TextAlignment = ADControlsLib.Windows.Forms.LxLedControl.Alignment.Right;
            this.ledAllTags.TotalCharCount = 10;
            // 
            // lblAllTags
            // 
            this.lblAllTags.AutoSize = true;
            this.lblAllTags.Location = new System.Drawing.Point(200, 66);
            this.lblAllTags.Name = "lblAllTags";
            this.lblAllTags.Size = new System.Drawing.Size(111, 20);
            this.lblAllTags.TabIndex = 2280;
            this.lblAllTags.Text = "All Tags(tags):";
            this.lblAllTags.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // pnlMsg
            // 
            this.pnlMsg.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlMsg.Controls.Add(this.ledCurrentAnt);
            this.pnlMsg.Controls.Add(this.lblCurrentAnt);
            this.pnlMsg.Controls.Add(this.nudInventoryInterval);
            this.pnlMsg.Controls.Add(this.nudInventoryCount);
            this.pnlMsg.Controls.Add(this.lblInventoryCount);
            this.pnlMsg.Controls.Add(this.nudRunTimes);
            this.pnlMsg.Controls.Add(this.lblRunTimes);
            this.pnlMsg.Controls.Add(this.nudMaxTag);
            this.pnlMsg.Controls.Add(this.ledAllTimes);
            this.pnlMsg.Controls.Add(this.lblAllTimes);
            this.pnlMsg.Controls.Add(this.lblInventoryInterval);
            this.pnlMsg.Controls.Add(this.lblMaxTag);
            this.pnlMsg.Controls.Add(this.ledInventoryTimes);
            this.pnlMsg.Controls.Add(this.lblInventoryTimes);
            this.pnlMsg.Controls.Add(this.ledInventoryTags);
            this.pnlMsg.Controls.Add(this.lblInventoryTags);
            this.pnlMsg.Controls.Add(this.ledAllTags);
            this.pnlMsg.Controls.Add(this.lblAllTags);
            this.pnlMsg.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlMsg.Location = new System.Drawing.Point(0, 0);
            this.pnlMsg.Name = "pnlMsg";
            this.pnlMsg.Size = new System.Drawing.Size(900, 126);
            this.pnlMsg.TabIndex = 74;
            // 
            // listViewEPC
            // 
            this.listViewEPC.AutoArrange = false;
            this.listViewEPC.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.cNumber,
            this.cPC,
            this.cEPC,
            this.cCRC,
            this.cDATA,
            this.cCnt,
            this.cAnt,
            this.cRssi});
            this.listViewEPC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.listViewEPC.FullRowSelect = true;
            this.listViewEPC.HideSelection = false;
            this.listViewEPC.Location = new System.Drawing.Point(0, 126);
            this.listViewEPC.MultiSelect = false;
            this.listViewEPC.Name = "listViewEPC";
            this.listViewEPC.Size = new System.Drawing.Size(900, 512);
            this.listViewEPC.TabIndex = 78;
            this.listViewEPC.UseCompatibleStateImageBehavior = false;
            this.listViewEPC.View = System.Windows.Forms.View.Details;
            // 
            // cNumber
            // 
            this.cNumber.Text = "";
            this.cNumber.Width = 30;
            // 
            // cPC
            // 
            this.cPC.Text = "PC";
            this.cPC.Width = 50;
            // 
            // cEPC
            // 
            this.cEPC.Text = "EPC";
            this.cEPC.Width = 440;
            // 
            // cCRC
            // 
            this.cCRC.Text = "CRC";
            this.cCRC.Width = 0;
            // 
            // cDATA
            // 
            this.cDATA.Text = "DATA";
            this.cDATA.Width = 0;
            // 
            // cCnt
            // 
            this.cCnt.Text = "Count";
            this.cCnt.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.cCnt.Width = 70;
            // 
            // cAnt
            // 
            this.cAnt.Text = "Ant";
            this.cAnt.Width = 40;
            // 
            // cRssi
            // 
            this.cRssi.Text = "RSSI";
            this.cRssi.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.cRssi.Width = 70;
            // 
            // saveFileDialog
            // 
            this.saveFileDialog.DefaultExt = "txt";
            this.saveFileDialog.FileName = "EPCList";
            this.saveFileDialog.Filter = "Text Files（*.txt）|*.txt";
            this.saveFileDialog.RestoreDirectory = true;
            // 
            // btnToggleAutoCycle
            // 
            this.btnToggleAutoCycle.Location = new System.Drawing.Point(644, 3);
            this.btnToggleAutoCycle.Name = "btnToggleAutoCycle";
            this.btnToggleAutoCycle.Size = new System.Drawing.Size(160, 35);
            this.btnToggleAutoCycle.TabIndex = 39;
            this.btnToggleAutoCycle.Text = "Start Auto Cycle";
            this.btnToggleAutoCycle.UseVisualStyleBackColor = true;
            this.btnToggleAutoCycle.Click += new System.EventHandler(this.btnToggleAutoCycle_Click);
            // 
            // ucMReadDemo
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.Controls.Add(this.listViewEPC);
            this.Controls.Add(this.pnlAction);
            this.Controls.Add(this.pnlMsg);
            this.Font = new System.Drawing.Font("Microsoft YaHei", 9F);
            this.Name = "ucMReadDemo";
            this.Size = new System.Drawing.Size(900, 680);
            this.pnlAction.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ledCurrentAnt)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudInventoryInterval)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudInventoryCount)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudRunTimes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nudMaxTag)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledAllTimes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledInventoryTimes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledInventoryTags)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ledAllTags)).EndInit();
            this.pnlMsg.ResumeLayout(false);
            this.pnlMsg.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel pnlAction;
        private System.Windows.Forms.Button btnClearScreen;
        private System.Windows.Forms.Button btnReadMultiple;
        private System.Windows.Forms.Timer tmrClock;
        private System.Windows.Forms.Button btnExport;
        private System.Windows.Forms.Label lblInventoryTags;
        private System.Windows.Forms.Label lblInventoryTimes;
        private System.Windows.Forms.Label lblMaxTag;
        private ADControlsLib.Windows.Forms.LxLedControl ledInventoryTimes;
        private ADControlsLib.Windows.Forms.LxLedControl ledInventoryTags;
        private ADControlsLib.Windows.Forms.LxLedControl ledAllTags;
        private System.Windows.Forms.Label lblAllTags;
        private System.Windows.Forms.Button btnSingleRead;
        private System.Windows.Forms.Label lblInventoryInterval;
        private ADControlsLib.Windows.Forms.LxLedControl ledAllTimes;
        private System.Windows.Forms.Label lblAllTimes;
        private System.Windows.Forms.NumericUpDown nudMaxTag;
        private System.Windows.Forms.NumericUpDown nudRunTimes;
        private System.Windows.Forms.Label lblRunTimes;
        private System.Windows.Forms.NumericUpDown nudInventoryCount;
        private System.Windows.Forms.Label lblInventoryCount;
        private System.Windows.Forms.NumericUpDown nudInventoryInterval;
        private System.Windows.Forms.Label lblCurrentAnt;
        private ADControlsLib.Windows.Forms.LxLedControl ledCurrentAnt;
        private System.Windows.Forms.Panel pnlMsg;
        private System.Windows.Forms.ListView listViewEPC;
        private System.Windows.Forms.ColumnHeader cNumber;
        private System.Windows.Forms.ColumnHeader cPC;
        private System.Windows.Forms.ColumnHeader cEPC;
        private System.Windows.Forms.ColumnHeader cCRC;
        private System.Windows.Forms.ColumnHeader cDATA;
        private System.Windows.Forms.ColumnHeader cCnt;
        private System.Windows.Forms.ColumnHeader cAnt;
        private System.Windows.Forms.ColumnHeader cRssi;
        private System.Windows.Forms.SaveFileDialog saveFileDialog;
        private System.Windows.Forms.Button btnToggleAutoCycle;
    }
}
